### ISSUE TITLE
`ad*` files are blocked by some ad blockers

### ISSUE THREAD

**Issue by emma-sg** [fightforthefuture/countdown-widget#2]
On the widget that is configured to use the `ad` animation, some ad blockers (AdBlock, AdBlock Plus, uBlock are the ones I've tested) block the files `ad.min.js` and `ad.min.css`. This results in the widget looking terrible and being useless. With those files missing, the widget looks like this: 
![screen shot 2015-02-01 at 6 57 26 pm](https://cloud.githubusercontent.com/assets/5727389/5994503/7f643bde-aa44-11e4-802f-f99cda4850e9.png) 
on the Internet Countdown page.
This could be fixed by renaming the files that have `ad` as part of their names.

**Comment by holmesworcester** [comment]
Thanks for catching this!

–Holmes

**Comment by 1RV34** [comment]
I would like to note that AdBlock Plus does not have this issue.
Tested with latest version of EasyList as of the time of this comment.

Edit: Tho you tested it with ABP too and did get the issue?

Edit 2: Tested via a JSFiddle http://fiddle.jshell.net/pqngsq7L/ as the preview on the site doesn't seem to be loaded in via the script code that is being shared.

**Comment by ChrisAntaki** [comment]
Ghostery is also fine

**Comment by 1RV34** [comment]
Just found out that I don't see an ad.min.js or ad.min.css loaded in via network, only the widget.min.js. Am I missing something?

**Comment by ChrisAntaki** [comment]
The `ad` name is for a specific template

**Comment by ChrisAntaki** [comment]
The fourth widget listed here: https://www.battleforthenet.com/countdown/#sites

**Comment by emma-sg** [comment]
This has been fixed, has it not? I can't find the `ad` files anymore, and it seems to work fine now.

Edit: Yes, this was fixed in 5f0cf6b7dec2bba755d9723af4173dcff9942145.

**Comment by rubbingalcoholic** [comment]
Sorry, I fixed this awhile ago but forgot to update this.

**Comment by rubbingalcoholic** [comment]
BTW thanks for reporting @EdenSG ! :+1:

**Comment by emma-sg** [comment]
No problem! :)

**Comment by ChrisAntaki** [comment]
Nice, thanks guys!

**Comment by 1RV34** [comment]
> The ad name is for a specific Widget template

I was aware of that, what I meant was when using that template it wasn't loading in an ad.min.js for me, but I believe that was because it just was fixed. :smile:

**Comment by ChrisAntaki** [comment]
Thanks for bumping the issue @1RV34
