### ISSUE TITLE
javascript NOT working

### ISSUE THREAD

**Issue by geofflau** [fightforthefuture/countdown-widget#4]
I have tried several times to put the countdown clock on my site an it does not show up either in Firefox or Safari 6.2.3. www.geoffreylaurence.com/directory.html. Any idea why?

**Comment by ChrisAntaki** [comment]
Hey @geofflau - please update your embed code to the following:

``` html
<script type="text/javascript">
var _cd_options = {
    theme: 'blue', // or 'red'
    elementId: '_cd_container'
}
</script>
<script src="https://fightforthefuture.github.io/countdown-widget/widget.min.js" async></script>
```

**Comment by geofflau** [comment]
Thanks Chris ­ I'm afraid it made no differenceŠ script still not working
for some reason.

Please check the page:  www.geoffreylaurence.com/directory.html

it should be showing above Edward Snowden's christmas message

```
     -- 
```

....G....

From:  Chris Antaki notifications@github.com
Reply-To:  fightforthefuture/countdown-widget
<reply+00a5526958dd9a7e85346f774d1c236c793ee406b6b0bb4292cf0000000110e8de6e9
2a169ce035cbe91@reply.github.com>
Date:  Tuesday, February 3, 2015 12:07 PM
To:  fightforthefuture/countdown-widget
countdown-widget@noreply.github.com
Cc:  Geoffrey Laurence geofflaurence@mac.com
Subject:  Re: [countdown-widget] javascript NOT working (#4)

Hey @geofflau https://github.com/geofflau  - please update your embed code
to the following:

<script type="text/javascript"><script type="text/javascript">var
_cd_options = {    theme: 'blue', // or 'red'    elementId:
'_cd_container'}</script>

<script 
src="https://fightforthefuture.github.io/countdown-widget/widget.min.js"
async></script>

‹
Reply to this email directly or view it on GitHub
<https://github.com/fightforthefuture/countdown-widget/issues/4#issuecomment
-72713303> .

**Comment by ChrisAntaki** [comment]
Hey @geofflau - it looks like this line got duplicated:

``` html
<script type="text/javascript">
```

Please try updating your embed to not repeat this line. Thanks!

**Comment by ChrisAntaki** [comment]
Aw yeah, I see it on there. :+1:

**Comment by geofflau** [comment]
Great! thanks for your help :o)

best,

```
     -- 
```

....G....

From:  Chris Antaki notifications@github.com
Reply-To:  fightforthefuture/countdown-widget
<reply+00a55269d35f954f7a3769ce6cf94a002639b18865cb441292cf0000000110e8e2e59
2a169ce035cbe91@reply.github.com>
Date:  Tuesday, February 3, 2015 12:26 PM
To:  fightforthefuture/countdown-widget
countdown-widget@noreply.github.com
Cc:  Geoffrey Laurence geofflaurence@mac.com
Subject:  Re: [countdown-widget] javascript NOT working (#4)

Aw yeah, I see it on there.

‹
Reply to this email directly or view it on GitHub
<https://github.com/fightforthefuture/countdown-widget/issues/4#issuecomment
-72716788> .
