### ISSUE TITLE
In a major policy shift, FCC will regulate Internet as a public utility (report)

### ISSUE THREAD

**Issue by eossipov** [fightforthefuture/countdown-widget#5]
http://venturebeat.com/2015/02/02/in-a-major-policy-shift-fcc-will-regulate-internet-as-a-public-utility-report/#

YOU ALL ARE THE BEST THERE ARE IN THE WORLD!!!

**Comment by holmesworcester** [comment]
thanks thanks thanks! 

not over yet though. hang in there!

**Comment by ChrisAntaki** [comment]
Thanks @eossipov

**Comment by rubbingalcoholic** [comment]
Thanks @eossipov! (super extra thanks if you're the same user on Twitter who has been hyping us so much, we really appreciate it :)

**Comment by eossipov** [comment]
Yea same me, and activism rocks, aspwired, Anacortes rocks, global
strategic concerns and a few others.  Gotta love automation  :)
