### ISSUE TITLE
Net Neutrality Code

### ISSUE THREAD

**Issue by sunrisemahler** [fightforthefuture/countdown-widget#8]
I am unable to get the code found here https://www.battleforthenet.com/countdown/#sites to work on my self-hosted wordpress site. Does anyone have any ideas why this would not be working on wordpress?

**Comment by mikemorris** [comment]
@sunrisemahler That link is for a campaign from several years ago, check out the widget for 2017 at https://github.com/fightforthefuture/battleforthenet-widget!
